name: Lint and Prettier

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  lint_and_prettier_job:
    uses: NovaPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '20'
      pkg_manager: 'pnpm'
      install: 'pnpm i'
      name: 'lint'
      command_one: 'pnpm lint'
      command_one_name: 'Lint code.'
      command_two: 'pnpm prettier'
      command_two_name: 'Prettier code.'
      checkout_recursive: false
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
