name: Test

on:
  pull_request:
    branches: [main, stable]
  workflow_dispatch:

jobs:
  test:
    uses: NovaPlay-Gaming/workflows/.github/workflows/nodejs_commands.yml@main
    with:
      node_version: '20'
      pkg_manager: 'pnpm'
      install: 'pnpm i'
      name: 'test'
      command_one: 'pnpm test'
      command_one_name: 'Test'
      checkout_recursive: false
    secrets:
      NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
